# Generated by Django 6.0.2 on 2026-02-17 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(choices=[('COMPORTAMENTO', 'Comportamento'), ('ENTREGAS', 'Entregas'), ('TRABALHO_EQUIPE', 'Trabalho em equipe')], max_length=30)),
                ('tipo_item_avaliacao_desempenho', models.TextField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de Item de Avaliação de Desempenho',
                'verbose_name_plural': 'Tipos de Itens de Avaliação de Desempenho',
                'ordering': ['dimensao'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_competencia', models.DateField()),
                ('status_avaliacao', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_ELABORACAO', 'Em elaboração'), ('EM_AVALIACAO', 'Em avaliação'), ('CONCLUIDA', 'Concluída')], default='CRIADA', max_length=30)),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sugestoes_supervisor', models.TextField(blank=True, null=True)),
                ('observacoes_avaliado', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_recebida', to='avaliacao_desempenho.colaborador')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_supervisionada', to='avaliacao_desempenho.colaborador')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Desempenho',
                'ordering': ['-mes_competencia'],
                'unique_together': {('colaborador', 'mes_competencia')},
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='avaliacao_desempenho.avaliacaodesempenho')),
                ('tipo_item_avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='avaliacao_desempenho.tipoitemavaliacaodesempenho')),
            ],
            options={
                'verbose_name': 'Item de Avaliação de Desempenho',
                'verbose_name_plural': 'Itens de Avaliações de Desempenho',
                'ordering': ['tipo_item_avaliacao_desempenho'],
            },
        ),
    ]
